service: my-express-application

provider: 
  name: aws
  runtime: nodejs6.10

functions:
    hello: 
      handler: handler.hello
      description: what hello function does 
      events: 
        - http: 
            path: /
            method: get
    imageResize: 
      handler: handler.imageResize
      events:
        - http: 
            path: /imageResize
            method: get
    createUser:
      handler: handler.users
      events:
        - http: 
            path: /users/create
            method: post
        - http: 
            path: /users/update
            method: put
        - http:
            path: /users/delete
            method: delete
    hello2:
      handler: handler.hello2
      events:
        - http: 
            path: /hello
            method: get



  
        


